### ISSUE TITLE
Installed using Ubuntu 20.04

### ISSUE THREAD

**Issue by jimmodo** [kendfinger/asset-cache-tool#4]
Hi, 

I tried installing using Ubuntu 20.04, this included installing Homebrew via the homebrew method on their website and installing GCC, compiler tools, swift, and python. Are there any other required packages to install this? Thanks!

**Comment by kendfinger** [comment]
Hello! Right now I don't believe there is support for installing via Homebrew on Linux. You should only need to download a Linux binary from releases: https://github.com/kendfinger/asset-cache-tool/releases/download/v0.0.1/asset-cache-tool.linux-amd64

Let me know if this works, if not I would be happy to help.
